# Generated by Django 4.2.6 on 2023-10-16 19:18

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='navigation',
            field=wagtail.fields.StreamField([('navigation', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('href', wagtail.blocks.CharBlock()), ('button_page', wagtail.blocks.PageChooserBlock(required=False))]))], null=True, use_json_field=True),
        ),
    ]
