# Generated by Django 4.2.6 on 2023-10-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_navigation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='navigation',
            new_name='body',
        ),
    ]
