# Generated by Django 4.2.6 on 2023-11-01 22:00

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_body_homepage_navigation_homepage_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='clients',
            field=wagtail.fields.StreamField([('clients', wagtail.images.blocks.ImageChooserBlock())], null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='navigation',
            field=wagtail.fields.StreamField([('navigation', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('href', wagtail.blocks.CharBlock()), ('show', wagtail.blocks.BooleanBlock(default=True, required=False))]))], null=True, use_json_field=True),
        ),
    ]
