# Generated by Django 4.2.6 on 2023-11-01 22:02

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_homepage_clients_alter_homepage_navigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='clients',
            field=wagtail.fields.StreamField([('clients', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))], null=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='navigation',
            field=wagtail.fields.StreamField([('navigation', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('href', wagtail.blocks.CharBlock()), ('show', wagtail.blocks.BooleanBlock(default=True, required=False))])), ('gallery', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))], null=True, use_json_field=True),
        ),
    ]
