# Generated by Django 4.2.6 on 2023-11-01 22:03

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_homepage_clients_alter_homepage_navigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='clients',
            field=wagtail.fields.StreamField([('clients', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(required=False)))], null=True, use_json_field=True),
        ),
    ]
