# Generated by Django 4.2.6 on 2023-11-01 22:07

from django.db import migrations
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_homepage_clients_alter_homepage_navigation'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='clients',
            field=wagtail.fields.StreamField([('clients', wagtail.images.blocks.ImageChooserBlock())], null=True, use_json_field=True),
        ),
    ]
