# Generated by Django 4.2.6 on 2023-11-01 22:22

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_homepage_clients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='clients',
            field=wagtail.fields.StreamField([('client', wagtail.blocks.StructBlock([('client', wagtail.images.blocks.ImageChooserBlock())]))], null=True, use_json_field=True),
        ),
    ]
