# Generated by Django 4.2.6 on 2023-11-02 08:22

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_homepage_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_href',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_list_items',
            field=wagtail.fields.StreamField([('about_list_item', wagtail.blocks.StructBlock([('item', wagtail.blocks.CharBlock())]))], null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_subtitle1',
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_subtitle2',
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
