# Generated by Django 4.2.6 on 2023-11-02 09:16

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_homepage_why_us_accordion_homepage_why_us_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='why_us_title',
            field=wagtail.fields.RichTextField(max_length=100, null=True),
        ),
    ]
