# Generated by Django 4.2.6 on 2023-11-02 09:29

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_homepage_why_us_accordion'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='why_us_accordion',
            field=wagtail.fields.StreamField([('why_us_accordion', wagtail.blocks.StructBlock([('span', wagtail.blocks.CharBlock()), ('title', wagtail.blocks.CharBlock()), ('subtitle', wagtail.blocks.RichTextBlock())]))], null=True, use_json_field=True),
        ),
    ]
