# Generated by Django 4.2.6 on 2023-11-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_homepage_why_us_accordion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='why_us_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
