# Generated by Django 4.2.6 on 2023-11-02 22:50

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_homepage_skills_homepage_skills_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='services',
            field=wagtail.fields.StreamField([('service', wagtail.blocks.StructBlock([('icon', wagtail.blocks.CharBlock(help_text='https://boxicons.com/ example bx bxs-user')), ('title', wagtail.blocks.CharBlock()), ('subtitle', wagtail.blocks.RichTextBlock())]))], null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_subtitle',
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='services_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='skills',
            field=wagtail.fields.StreamField([('skill', wagtail.blocks.StructBlock([('skill_title', wagtail.blocks.CharBlock()), ('skill_value', wagtail.blocks.CharBlock())]))], null=True, use_json_field=True),
        ),
    ]
