# Generated by Django 4.2.6 on 2023-11-03 22:34

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_homepage_services_homepage_services_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='features',
            field=wagtail.fields.StreamField([('feature', wagtail.blocks.StructBlock([('icon', wagtail.blocks.CharBlock(help_text='https://boxicons.com/ example bx bxs-user')), ('title', wagtail.blocks.CharBlock()), ('subtitle', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('ul_list', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock(required=False)))]))], null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_subtitle',
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
