# Generated by Django 4.2.6 on 2023-11-03 22:50

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_homepage_features_homepage_features_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='features',
            field=wagtail.fields.StreamField([('feature', wagtail.blocks.StructBlock([('icon', wagtail.blocks.CharBlock(help_text='https://icons.getbootstrap.com/ example bi bi-binoculars')), ('title', wagtail.blocks.CharBlock()), ('subtitle', wagtail.blocks.RichTextBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock()), ('ul_list', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock(required=False)))]))], null=True, use_json_field=True),
        ),
    ]
