# Generated by Django 4.2.6 on 2023-11-10 07:46

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_homepage_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='team',
            field=wagtail.fields.StreamField([('team', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock()), ('profession', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('subtitle', wagtail.blocks.RichTextBlock(required=False))]))], null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='team_subtitle',
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='team_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
