# Generated by Django 4.2.6 on 2023-11-10 08:10

from django.db import migrations
import streams.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_homepage_team_homepage_team_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='team',
            field=wagtail.fields.StreamField([('team', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock()), ('profession', wagtail.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('subtitle', wagtail.blocks.RichTextBlock(required=False)), ('socials', wagtail.blocks.ListBlock(streams.blocks.SocialLinkBlock, required=False))]))], null=True, use_json_field=True),
        ),
    ]
