# Generated by Django 4.2.6 on 2023-11-10 09:45

from django.db import migrations, models
import streams.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_homepage_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='pricing',
            field=wagtail.fields.StreamField([('pricing', wagtail.blocks.StructBlock([('plan', wagtail.blocks.CharBlock()), ('currency', wagtail.blocks.CharBlock()), ('price', wagtail.blocks.CharBlock()), ('duration', wagtail.blocks.CharBlock()), ('button_url', wagtail.blocks.CharBlock()), ('button_name', wagtail.blocks.CharBlock()), ('features', wagtail.blocks.ListBlock(streams.blocks.PricingFeaturesBlock))]))], null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pricing_subtitle',
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='pricing_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
