# Generated by Django 4.2.6 on 2023-11-10 09:48

from django.db import migrations
import streams.blocks
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_homepage_pricing_homepage_pricing_subtitle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='pricing',
            field=wagtail.fields.StreamField([('pricing', wagtail.blocks.StructBlock([('plan', wagtail.blocks.CharBlock()), ('currency', wagtail.blocks.CharBlock()), ('price', wagtail.blocks.CharBlock()), ('duration', wagtail.blocks.CharBlock()), ('button_url', wagtail.blocks.CharBlock()), ('button_name', wagtail.blocks.CharBlock()), ('featured_box', wagtail.blocks.CharBlock(help_text=" class name 'featured' for a featured box", required=False)), ('features', wagtail.blocks.ListBlock(streams.blocks.PricingFeaturesBlock))]))], null=True, use_json_field=True),
        ),
    ]
