# Generated by Django 4.2.6 on 2023-11-10 10:19

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_homepage_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='faq',
            field=wagtail.fields.StreamField([('faq', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('subtitle', wagtail.blocks.RichTextBlock())]))], null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faq_subtitle',
            field=wagtail.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='faq_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
