# Generated by Django 4.2.6 on 2023-11-20 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_formpage_formfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formfield',
            old_name='form_page',
            new_name='page',
        ),
    ]
