# Generated by Django 4.2.6 on 2023-11-20 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_contactpage_alter_formfield_page_delete_formpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfield',
            name='page',
        ),
        migrations.DeleteModel(
            name='ContactPage',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
    ]
